### ISSUE TITLE
Signatory on linux fails to start due to panic during configuration parsing

### ISSUE THREAD

**Issue by stephengaudet** [ecadlabs/signatory#346]
steps to reproduce: 
1. on a linux workstation `make clean` and then `make` of branch main, or, on a macbook, you'll need to run image tag `main-arm64`
2. simply need a yaml config file with at least 1 pkh within the `tezos` declaration.  it does not appear to be specific to a pkh value, both tz1WGcYos3hL7GXYXjKrMnSFdkT7FyXnFBvf and tz3chb8Jgaw1XdiZXfzSYfVkHiq1YSAvcRoy fail to parse

expected:
Signatory server starts

actual: 
panic and fail to start. the stack shows after unmarshalling the pkh, the gotez module attempts to then _en_code the pk, and it is here the panic is raised. note, works fine on my macbook.  local build using makefile fails on Dan's workstation, so, looks linux specific

```
 ⠿ Container signatory                   Created                                                                                                                                                  0.1s
Attaching to signatory
signatory  | panic: reflect: call of reflect.Value.Bytes on array Value [recovered]
signatory  | 	panic: reflect: call of reflect.Value.Bytes on array Value
signatory  | 
signatory  | goroutine 1 [running]:
signatory  | gopkg.in/yaml%2ev3.handleErr(0x400071fb98)
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x84
signatory  | panic({0xd557c0, 0x40000a00d8})
signatory  | 	/usr/local/go/src/runtime/panic.go:838 +0x20c
signatory  | reflect.flag.mustBe(...)
signatory  | 	/usr/local/go/src/reflect/value.go:223
signatory  | reflect.Value.Bytes({0xd993e0?, 0x40003384c8?, 0x40004ca400?})
signatory  | 	/usr/local/go/src/reflect/value.go:291 +0xd0
signatory  | github.com/ecadlabs/gotez/encoding.encodeValue({0x127d2a0, 0x4000645830}, {0xddb600?, 0x40003384c8?, 0x1000000000000?}, 0x400050e208, {0x0?, 0x0?, 0x0?})
signatory  | 	/go/pkg/mod/github.com/ecadlabs/gotez@v1.0.0/encoding/encode.go:160 +0x3c0
signatory  | github.com/ecadlabs/gotez/encoding.(*EnumRegistry).tryEncode(0x4000032080, {0x127d2a0, 0x4000645830}, {0xda2b00?, 0x40002d8630?, 0xd3d56fdd2718e76c?}, 0xee40?)
signatory  | 	/go/pkg/mod/github.com/ecadlabs/gotez@v1.0.0/encoding/enum.go:100 +0x2bc
signatory  | github.com/ecadlabs/gotez/encoding.encodeValue({0x127d2a0, 0x4000645830}, {0xce9280?, 0x40002d8630?, 0x40004ca400?}, 0x400050e208, {0x196bf00?, 0x18bd620?, 0x400071ef18?})
signatory  | 	/go/pkg/mod/github.com/ecadlabs/gotez@v1.0.0/encoding/encode.go:185 +0x480
signatory  | github.com/ecadlabs/gotez/encoding.Encode({0x127d2a0, 0x4000645830}, {0xce9280?, 0x40002d8630?}, {0x0?, 0x30?, 0x400010a5a0?})
signatory  | 	/go/pkg/mod/github.com/ecadlabs/gotez@v1.0.0/encoding/encode.go:201 +0x114
signatory  | github.com/ecadlabs/gotez.(*EncodedPublicKeyHash).UnmarshalText(0x4000338498, {0x400010a5a0?, 0x24?, 0xca2184?})
signatory  | 	/go/pkg/mod/github.com/ecadlabs/gotez@v1.0.0/key.go:124 +0x234
signatory  | gopkg.in/yaml%2ev3.(*decoder).scalar(0xd98fe0?, 0x400026f220, {0xd98fe0?, 0x4000338498?, 0x10001ec80?})
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:603 +0x1118
signatory  | gopkg.in/yaml%2ev3.(*decoder).unmarshal(0x40003e0000, 0x400026f220, {0xd98fe0?, 0x4000338498?, 0x4000645800?})
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:508 +0x324
signatory  | gopkg.in/yaml%2ev3.(*decoder).mapping(0x40003e0000, 0x400026f0e0, {0xdcec80?, 0x40000bc008?, 0xd16c00?})
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:832 +0x684
signatory  | gopkg.in/yaml%2ev3.(*decoder).unmarshal(0x40003e0000, 0x400026f0e0, {0xdcec80?, 0x40000bc008?, 0x400071f548?})
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:510 +0x340
signatory  | gopkg.in/yaml%2ev3.(*decoder).mappingStruct(0x40003e0000, 0x40004454a0, {0xe2dba0?, 0x40000bc000?, 0x400071f848?})
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:935 +0xa14
signatory  | gopkg.in/yaml%2ev3.(*decoder).mapping(0x40003e0000, 0x40004454a0, {0xe2dba0?, 0x40000bc000?, 0x0?})
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:786 +0x90
signatory  | gopkg.in/yaml%2ev3.(*decoder).unmarshal(0x40003e0000, 0x40004454a0, {0xe2dba0?, 0x40000bc000?, 0x400071fa58?})
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:510 +0x340
signatory  | gopkg.in/yaml%2ev3.(*decoder).document(0xe2dba0?, 0x40000bc000?, {0xe2dba0?, 0x40000bc000?, 0x0?})
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:527 +0x80
signatory  | gopkg.in/yaml%2ev3.(*decoder).unmarshal(0x40003e0000, 0x4000445360, {0xe2dba0?, 0x40000bc000?, 0xffff6a0ef118?})
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:498 +0x390
signatory  | gopkg.in/yaml%2ev3.unmarshal({0x40000da000, 0x1e6, 0x200}, {0xd4e260?, 0x40000bc000}, 0xa0?)
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:167 +0x414
signatory  | gopkg.in/yaml%2ev3.Unmarshal(...)
signatory  | 	/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:89
signatory  | github.com/ecadlabs/signatory/pkg/config.(*Config).Read(0x4000502160?, {0xeb05a2?, 0xea4f19?})
signatory  | 	/go/src/github.com/ecadlabs/signatory/pkg/config/config.go:67 +0x48
signatory  | github.com/ecadlabs/signatory/cmd/commands.NewRootCommand.func1(0x40000c6300?, {0xe99405?, 0x0?, 0x0?})
signatory  | 	/go/src/github.com/ecadlabs/signatory/cmd/commands/root.go:47 +0x1a8
signatory  | github.com/spf13/cobra.(*Command).execute(0x40000c6300, {0x196bf00, 0x0, 0x0})
signatory  | 	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:891 +0x53c
signatory  | github.com/spf13/cobra.(*Command).ExecuteC(0x40000c6000)
signatory  | 	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x368
signatory  | github.com/spf13/cobra.(*Command).Execute(...)
signatory  | 	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
signatory  | main.main()
signatory  | 	/go/src/github.com/ecadlabs/signatory/cmd/signatory/main.go:49 +0xfc
signatory exited with code 2
```

**Comment by AbineshECAD** [comment]
My initial analysis.
https://ecadlabs.slack.com/archives/CL1NK8526/p1682548224151379

It would be better if Eugene added a fix for this issue.

**Comment by e-asphyx** [comment]
I thought it's a Go version issue and it was discussed before
